apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.rules: |-
    groups:
      - name: Postgree
        rules:
          - alert: PostgreeDown
            expr: pg_up != 1 or absent(pg_up) == 1
            for: 10s
            labels:
              team: database
            annotations:
              titulo: Banco de dados Postgree fora do ar
              description: O Banco de dados Postgree está fora do ar
      - name: Web
        rules: 
          - alert: WebComMuitoAcesso
            expr: rate(http_requests_total{path="/"}[1m]) > 1
            for: 20s
            labels:
              team: web
            annotations:
              titulo: Muitas requisições na aplicação
              description: A aplicação web está com muitas requisições.
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval: 15s
      evaluation_interval: 30s
      scrape_timeout: "10s"

      external_labels:
        monitor: codelab    

    rule_files:
      - alert-rulers.rules

    scrape_configs: 
      - job_name: 'Prometheus'
        static_configs:
          - targets: ['localhost:9090']
            labels:
              grupo: 'Prometheus'

      - job_name: 'Postgree'         
        static_configs:    
          - targets: ['postgreeexporter:9187']
            labels:
              grupo: 'Postgree'

      - job_name: 'Web'
        static_configs:
          - targets: ['kubenews:8080']
            labels:
              grupo: 'web'

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alert-manager.yaml: |-
    global:
    route:
      receiver: Default
      group_by: ['alertname']
      group_wait: 15s
      group_interval: 15s
      repeat_interval: 1m
      
      routes:
      - receiver: AlertaDatabase
        match:
          team: database

      - receiver: AlertaWeb
        match:
          team: web

    receivers:
    - name: Default
      telegram_configs:
      - bot_token: 7253922807:AAHCtMakPSOgEw9YJ73EJUh5uhjPKCL2nvY
        api_url: https://api.telegram.org
        chat_id: 1225103273
        parse_mode: ''
        message: "{{range .Alerts}}{{ .Annotations.description }}\n{{ end }}"

    - name: AlertaDatabase
      telegram_configs:
      - bot_token: 7253922807:AAHCtMakPSOgEw9YJ73EJUhjPKCL2nvY
        api_url: https://api.telegram.org
        chat_id: 1225103273
        parse_mode: ''
        message: "{{range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

    - name: AlertaWeb
      telegram_configs:
      - bot_token: 7253922807:AAHCtMakPSOgEw9YJ73EJUhjPKCL2nvY
        api_url: https://api.telegram.org
        chat_id: 1225103273
        parse_mode: ''
        message: "{{range .Alerts}}{{ .Annotations.description }}\n{{ end }}"
