apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgree-pv
  namespace: default

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgree/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgree-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgree-pv
  storageClassName: standard

